### ISSUE TITLE
Gnusocial support?

### ISSUE THREAD

**Issue by scroom** [birdieapp/birdie#102]
I've got a question. Will Birdie 2.0 support Gnusocial (quitter.se and so on)?

Yours

**Comment by DanScharon** [comment]
+1 this would be great

**Comment by nathandyer** [comment]
Hi! I'm sorry, but this feature just isn't within the scope of the project. Birdie is very tightly coupled with Twitter, and supporting other services isn't part of the project plans. Thank you for your report!
