### ISSUE TITLE
Shadows of media preview dialogs broken on Gtk 3.14

### ISSUE THREAD

**Issue by mank319** [birdieapp/birdie#107]
I am using `birdie-granite` on elementary OS Freya and since the update to `Gtk 3.14` shadows around the preview dialogs for images and videos appear somewhat misplaced:
![birdie_preview_bug](https://cloud.githubusercontent.com/assets/3366745/5788729/9c3003c8-9e47-11e4-9bb1-6e9c549bb5eb.png)

**Comment by ivonunes** [comment]
The current Birdie codebase doesn't have any similarities to the code used in Birdie 1.1. As such, this bug no longer exists.
