### ISSUE TITLE
lists not implemented

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [birdieapp/birdie#108]
![schermata-birdie](https://cloud.githubusercontent.com/assets/10689739/5889464/1787d870-a429-11e4-9405-14e4021bec40.png)

compiled from source on
Linux Host-001 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 GNU/Linux

**Comment by ivonunes** [comment]
Actually, lists haven't been implemented yet in Birdie 2.0. I'll mark this as an enhancement.

**Comment by nathandyer** [comment]
Lists have now been implemented in Birdie 2.0
