### ISSUE TITLE
New tweet window w/ shadow but no background

### ISSUE THREAD

**Issue by rtud** [birdieapp/birdie#109]
Running on eOS 0.3 Freya

![Birdie Bug: No background](https://s3.amazonaws.com/f.cl.ly/items/0p0p3h3p150Z313S2S09/Screenshot%20from%202015-02-03%2015%3A18%3A23.png)

**Comment by geocool** [comment]
I can confirm this bug as well on elementary OS Beta 2 fresh install.

**Comment by nathandyer** [comment]
Hi! Yes, that was a nasty little big caused by the old Granite LightWindow widget that we used. That is all fixed in the upcoming 2.0 release. Thank you for your report!
