### ISSUE TITLE
Help not able configure on ubuntu 14.04

### ISSUE THREAD

**Issue by mohdalam** [birdieapp/birdie#114]
```./configure.ac: 1: ./configure.ac: Syntax error: word unexpected (expecting ")")```

**Comment by drewlustro** [comment]
You must use `autoconf` to build. I'm on Ubuntu 14.04. Here's what I installed to build Birdie:

`sudo apt-get install auto-conf gnome-tools yelp-tools python-pip`

And of course, make sure you have all the other prerequisite libs specified in the wiki:

`sudo apt-get install cmake valac libgtk-3-dev librest-dev libjson-glib-dev libnotify-dev libcanberra-dev libx11-dev libwebkitgtk-3.0-dev libsqlite3-dev libxtst-dev libpurple-dev libgee-dev libdbusmenu-gtk-dev libgtksourceview-3.0-dev libunity-dev libmessaging-menu-dev libgirepository1.0-dev libindicate-dev`

Then let `autoconf` and `automake` do their magic by running the provided script:

`./autogen.sh`

Finally, you can `make` and `sudo make install`

**Comment by nathandyer** [comment]
Hi! I'm sorry, but we recently announced that we are focusing on elementary OS and are dropping official support for all other Linux platforms. I invite you to [read our announcement post](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html) for more information. Thank you!
