### ISSUE TITLE
Double commands in titlebar

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [birdieapp/birdie#115]
When using kwin under debian mate i have double commands (close minimize ).

See in top right
![schermata-birdie](https://cloud.githubusercontent.com/assets/10689739/6948091/bfc03300-d8ab-11e4-8002-ba52baaa456b.png)

**Comment by Alessandro-Barbieri** [comment]
Seems that, when I switch from marco to kwin at startup, if birdie launches before kwin then birdie have 2 command bars.
When started after kwin then birdie is normal.

**Comment by nathandyer** [comment]
Hi! I'm sorry, but we have decided to focus on elementary OS, and are therefore dropping support for all other Linux platforms. Please check out our [announcement post](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html) for more information. Thank you for the report!
