### ISSUE TITLE
Birdie not using libnotify for notifications

### ISSUE THREAD

**Issue by proudh0n** [birdieapp/birdie#118]
I'm using Ubuntu 14.04 LTS and I recently installed Birdie. The problem that I have is that notifications appear on a normal window, like any other dialog:

![birdie_003](https://cloud.githubusercontent.com/assets/8055505/7245916/b7c63b92-e7f4-11e4-9661-eb1ac456bb6a.png)

I think birdie should use notify-send for showing the notifications.

**Comment by acutbal** [comment]
Hello,

It's the same for me, every new notification is showed on a normal window.
![captura de pantalla de 2015-04-30 13 26 01](https://cloud.githubusercontent.com/assets/2278584/7411891/ee70aff2-ef3c-11e4-8339-6a3263066f45.png)


Thank you very much!!

**Comment by nathandyer** [comment]
Hi! Thank you for the report! I'm happy to say that Birdie 2.0 does use libnotify exclusively for notifications, although I may be the bearer of bad news for you: we recently announced that we are focusing on elementary OS and are therefore dropping support for all other Linux platforms. You can [read out announcement post for more information](https://media.giphy.com/media/rl0FOxdz7CcxO/giphy.gif).
