### ISSUE TITLE
Strange black border

### ISSUE THREAD

**Issue by Kingbalou** [birdieapp/birdie#119]
![birdie](https://cloud.githubusercontent.com/assets/6079068/7270357/fa7436fa-e8db-11e4-92db-fea74f1b0b74.png)

I switched on linux4.0 on my Manjaro and now i've some strange black border.
On linux3.19, i've already seen that the windows border doesn't match with the real window border , like transparent extra border outside the window , and now it's black extra border. 

But everything is working :)

**Comment by proudh0n** [comment]
Correct me if I'm wrong, but you are using XFCE? Or any desktop environment that support CSD? This is a known bug when using GTk 3.16 apps on desktop environments that are not Gnome. Is not a bug from Birdie.

It's some kind of problem when drawing shadows, in fact, if you edit the theme.css and remove the shadow you will see that the border disappears.

Link to the bug report: https://mail.gnome.org/archives/gnome-shell-list/2015-April/msg00011.html
https://mail.gnome.org/archives/gnome-shell-list/2015-April/msg00003.html

**Comment by nathandyer** [comment]
Hi! Yes, @proudh0n is correct, this is not a bug in Birdie. Please note that we recently announced that we will be focusing on elementary OS and will therefore be dropping official support for all other Linux platforms. [Check out our announcement for more information](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html). Thank you!
