### ISSUE TITLE
ppa:birdie-team/stable is extrememly unstable on Elementary OS Freya.

### ISSUE THREAD

**Issue by qxlab** [birdieapp/birdie#122]
Tried for a day and finally removed.

Can reinstall and provide logs if this is not what usually happens (as in stability on Freya I mean).

**Comment by nathandyer** [comment]
The version in that PPA is over a year old and is very outdated. We're working on a new release and a new PPA. I'm going to go ahead and close this issue because it's referencing a very old version of Birdie that is no longer available (other than in that PPA). Thanks for your report!
