### ISSUE TITLE
Dependency Missing python2-socksipy-git

### ISSUE THREAD

**Issue by iamfreee** [birdieapp/birdie#125]
Hi,

I am trying installing birdie from yaourt (birdie-git) and it fails since python2-socksipy-git is missing.

Manjaro

**Comment by nathandyer** [comment]
Hi! This is going to be confusing, and I apologize, but Birdie is no longer using Python. It was originally written in Vala, then the original author decided to re-write it in Python, and when I took over development of the project I went back to the original Vala. So this is no longer a problem. Thanks for your report! And sorry for all the flip-flopping :)
