### ISSUE TITLE
New tweet window is transparent

### ISSUE THREAD

**Issue by bgcarlisle** [birdieapp/birdie#126]
![screenshot from 2015-10-04 15 22 05](https://cloud.githubusercontent.com/assets/3100614/10269668/b63c7d24-6aab-11e5-8ebe-d9856c41a84c.png)

Using birdie-granite v. 1.1 on elementary os Freya 0.3.1 (64-bit), the new tweet window is transparent, as illustrated above.

**Comment by nathandyer** [comment]
Hi! I'm happy to report that this issue has been fixed and will be included in the Birdie 2.0 release. Cheers!
