### ISSUE TITLE
Birdie does not remember position and size of window on re-opening

### ISSUE THREAD

**Issue by bgcarlisle** [birdieapp/birdie#127]
When I close birdie and reopen, the window is not the same size or location.

**Comment by codemusings** [comment]
Have you tried the latest build? It's working for me!

**Comment by bgcarlisle** [comment]
I'm using Birdie 1.1, the latest from ppa:birdie-team/stable

**Comment by codemusings** [comment]
I looked through the code. The handling of user settings was introduced with the 2.0 dev branch. So if you're feeling experimental you could check out the code from Github and build it from scratch :)

**Comment by nathandyer** [comment]
Hi! This is now working in Birdie 2.0 When you quit the app the settings are saved, and they are restored the next time you open the app. Cheers!

**Comment by bgcarlisle** [comment]
I just installed Birdie 2.0 and it still doesn't remember a window's position on re-opening ...
