### ISSUE TITLE
black corners in ubuntu near rounded corners of birdie

### ISSUE THREAD

**Issue by luntik2012** [birdieapp/birdie#130]
Using Ubuntu 15.10, looks like this http://tinypic.com/r/314p72a/8

**Comment by nathandyer** [comment]
Hi! I'm sorry, but we recently announced that were are focusing on making the best app possible for elementary OS, which means we are dropping official support for all other Linux platforms. [Please take a look at our announcement blog post](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html). Cheers!

**Comment by nmabhinandan** [comment]
![45013338](https://cloud.githubusercontent.com/assets/1548848/13009018/fea9c622-d1bf-11e5-8b95-a164ebeaf2cd.jpg)
