### ISSUE TITLE
Links are to strong

### ISSUE THREAD

**Issue by Haikuch** [birdieapp/birdie#136]
so for me, the important part of a tweet is the text, not the link. But in birdie the blue, mostly very long link (most tweets I read have links inside) is much too strong in contrast to the text. I would like to have the possibility to shorten the link and/or to change its color/font/etc

**Comment by nathandyer** [comment]
Hi! I'm happy to report that the links are now the same color as they text (although they do get slightly bolder when you hover them). We don't have any plans to allow custom colors, however. Cheers!
