### ISSUE TITLE
Showing "official account" checkmark icon is jarring

### ISSUE THREAD

**Issue by afcowie** [birdieapp/birdie#140]
Don't need to see the "official account" blue icon in the normal stream view. When clicking on a profile, sure, but not sliding by every other tweet if you just happen to follow a journalist or similar.

[it's visually jarring because it means the tweeter's name is not consistently left aligned; we generally try not to do that to people, HIG-wise]

Enjoying birdie! Thanks for your hard work.

AfC

**Comment by nathandyer** [comment]
I'm happy to report that this issue is fixed! Cheers.
