### ISSUE TITLE
Birdie is missing from AUR

### ISSUE THREAD

**Issue by TamasBarta** [birdieapp/birdie#141]
The website states that I can install Birdie from AUR with `yaourt -S birdie`, however I can't. `https://aur.archlinux.org/packages/birdie` says 404.

**Comment by TamasBarta** [comment]
Sorry, if I just mistaken a renaming. I'm aware of the presence of `birdie-git`, but that seemed to be an older version, maybe I'm wrong.

**Comment by nathandyer** [comment]
Hi! I'm sorry, but we have decided to focus on elementary OS, and we are therefore dropping official support for all other Linux platforms. Please read [our post for more information](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html).

**Comment by TamasBarta** [comment]
Hi! Thanks for the info! Good luck with Birdie on elementary!
