### ISSUE TITLE
Keyboard shorcut already in use

### ISSUE THREAD

**Issue by derixithy** [birdieapp/birdie#144]
When i start birdy it registeres itself to the keyboard shortcut Super+T
This shortcut however is on elementaryOS used for opening the terminal.

There seems to be no way to toggle this off or change it.
So now every time i open up Birdy i have to reregister my keyboard shortcut to the terminal again.

**Comment by nathandyer** [comment]
Hey! We actually decided to remove this feature, so the problem is fixed in 2.0. Thank you for the report!
