### ISSUE TITLE
Fedora support?

### ISSUE THREAD

**Issue by jacyzin** [birdieapp/birdie#148]
There's a possibility that the birdie have implementation for Fedora? Tnx.

**Comment by nathandyer** [comment]
Hi! It's possible for Birdie to run in Fedora, but honestly, you're not going to have a great experience. We [recently announced that we are only going to officially support elementary OS](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html). We recommend that users on other platforms try Corebird instead.
