### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by TuxNuX** [birdieapp/birdie#175]
Hello to you,
I use
```
git clone https://github.com/birdieapp/birdie.git
cd birdie
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr

```

> -- The C compiler identification is GNU 4.9.2
> -- The CXX compiler identification is GNU 4.9.2
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Found Vala: /usr/bin/valac  
> -- checking for a minimum Vala version of 0.22.1
> --   found Vala, version 0.30.1
> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
> -- Unity launcher support: OFF
> -- checking for modules 'gtk+-3.0;gtksourceview-3.0;granite;gee-0.8;rest-0.7;json-glib-1.0;libnotify;libcanberra;gdk-x11-3.0;webkitgtk-3.0;sqlite3;xtst;purple;gthread-2.0'
> --   found gtk+-3.0, version 3.14.8
> --   found gtksourceview-3.0, version 3.14.3
> --   found granite, version 0.3.1
> --   found gee-0.8, version 0.16.1
> --   found rest-0.7, version 0.7.92
> --   found json-glib-1.0, version 1.0.2
> --   found libnotify, version 0.7.6
> --   found libcanberra, version 0.30
> --   found gdk-x11-3.0, version 3.14.8
> --   found webkitgtk-3.0, version 2.4.9
> --   found sqlite3, version 3.9.1
> --   found xtst, version 1.2.2
> --   found purple, version 2.10.11
> --   found gthread-2.0, version 2.42.1
> -- GSettings schemas will be installed locally.
> -- GSettings shemas will be compiled.
> -- GSettings schemas will be installed into /usr/share/glib-2.0/schemas/
> -- Configuring done
> -- Generating done
```
make

```

> [  2%] Generating main.c, config.c, Birdie.c, API.c, Twitter.c, Tweet.c, User.c, Database.c, TwitterList.c, Cache.c, Widgets/TweetBox.c, Widgets/TweetList.c, Widgets/UnifiedWindow.c, Widgets/TweetDialog.c, Widgets/UserBox.c, Widgets/Dialogs.c, Widgets/Welcome.c, Widgets/Notebook.c, Widgets/MoreButton.c, Widgets/ListsView.c, Widgets/ListBox.c, Widgets/CompletionProvider.c, Widgets/ConversationsList.c, Widgets/ConversationView.c, Widgets/AccountsPopover.c, Media/Avatar.c, Media/GetMedia.c, Media/Parsing.c, Media/ShowMedia.c, Media/Imgur.c, Media/Cairo.c, Media/Pixbuf.c, Utils/Date.c, Utils/Notifications.c, Utils/Launcher.c, Utils/Networking.c, Utils/Downloader.c, Utils/Strings.c, Utils/Files.c, Utils/Logger.c, Utils/StatusIcon.c, Utils/System.c
> /home/patrice/Téléchargements/GIT/birdie/src/Widgets/TweetBox.vala:61.16-61.37: error: The type name `Granite.Widgets.Avatar' could not be found
>         public Granite.Widgets.Avatar avatar;
>                ^^^^^^^^^^^^^^^^^^^^^^
> /home/patrice/Téléchargements/GIT/birdie/src/Widgets/TweetDialog.vala:22.9-22.30: error: The type name `Granite.Widgets.Avatar' could not be found
>         Granite.Widgets.Avatar avatar;
>         ^^^^^^^^^^^^^^^^^^^^^^
> /home/patrice/Téléchargements/GIT/birdie/src/Widgets/UserBox.vala:28.17-28.38: error: The type name `Granite.Widgets.Avatar' could not be found
>         private Granite.Widgets.Avatar avatar;
>                 ^^^^^^^^^^^^^^^^^^^^^^
> /home/patrice/Téléchargements/GIT/birdie/src/Widgets/ConversationsList.vala:58.46-58.67: error: The type name `Granite.Widgets.Avatar' could not be found
>             var people = new HashMap<string, Granite.Widgets.Avatar>();
>                                              ^^^^^^^^^^^^^^^^^^^^^^
> /home/patrice/Téléchargements/GIT/birdie/src/Widgets/ConversationsList.vala:105.17-105.38: error: The type name `Granite.Widgets.Avatar' could not be found
>                 Granite.Widgets.Avatar avatar = people.get(name);
>                 ^^^^^^^^^^^^^^^^^^^^^^
> /home/patrice/Téléchargements/GIT/birdie/src/Widgets/ConversationsList.vala:107.17-107.38: error: The type name `Granite.Widgets.Avatar' could not be found
>                 Granite.Widgets.Avatar new_avatar = new Granite.Widgets.Avatar.from_pixbuf(pixbuf);
>                 ^^^^^^^^^^^^^^^^^^^^^^
> /home/patrice/Téléchargements/GIT/birdie/src/Birdie.vala:790.13-790.34: error: The type name `Granite.Widgets.Avatar' could not be found
>             Granite.Widgets.Avatar avatar = null;
>             ^^^^^^^^^^^^^^^^^^^^^^
> src/CMakeFiles/birdie.dir/build.make:94: recipe for target 'src/main.c' failed
> make[2]: *** [src/main.c] Error 1
> CMakeFiles/Makefile2:151: recipe for target 'src/CMakeFiles/birdie.dir/all' failed
> make[1]: *** [src/CMakeFiles/birdie.dir/all] Error 2
> Makefile:117: recipe for target 'all' failed
> make: *** [all] Error 2

my system is arch .x86_64

**Comment by dschense** [comment]
I get the same error.. anybody with a hint ?

**Comment by kriloleg** [comment]
And I have the same issue

**Comment by dschense** [comment]
getting this again and again. 

`[dschense@little build]$ make
[  2%] Generating main.c, config.c, Birdie.c, API.c, Twitter.c, Tweet.c, User.c, Database.c, TwitterList.c, Cache.c, Widgets/TweetBox.c, Widgets/TweetList.c, Widgets/UnifiedWindow.c, Widgets/TweetDialog.c, Widgets/UserBox.c, Widgets/Dialogs.c, Widgets/Welcome.c, Widgets/Notebook.c, Widgets/MoreButton.c, Widgets/ListsView.c, Widgets/ListBox.c, Widgets/CompletionProvider.c, Widgets/ConversationsList.c, Widgets/ConversationView.c, Widgets/AccountsPopover.c, Media/Avatar.c, Media/GetMedia.c, Media/Parsing.c, Media/ShowMedia.c, Media/Imgur.c, Media/Cairo.c, Media/Pixbuf.c, Utils/Date.c, Utils/Notifications.c, Utils/Launcher.c, Utils/Networking.c, Utils/Downloader.c, Utils/Strings.c, Utils/Files.c, Utils/Logger.c, Utils/StatusIcon.c, Utils/System.c
/home/dschense/Downloads/birdie-master/src/Widgets/TweetBox.vala:61.16-61.37: error: The type name `Granite.Widgets.Avatar' could not be found
        public Granite.Widgets.Avatar avatar;
               ^^^^^^^^^^^^^^^^^^^^^^
/home/dschense/Downloads/birdie-master/src/Widgets/TweetDialog.vala:22.9-22.30: error: The type name `Granite.Widgets.Avatar' could not be found
        Granite.Widgets.Avatar avatar;
        ^^^^^^^^^^^^^^^^^^^^^^
/home/dschense/Downloads/birdie-master/src/Widgets/UserBox.vala:28.17-28.38: error: The type name `Granite.Widgets.Avatar' could not be found
        private Granite.Widgets.Avatar avatar;
                ^^^^^^^^^^^^^^^^^^^^^^
/home/dschense/Downloads/birdie-master/src/Widgets/ConversationsList.vala:58.46-58.67: error: The type name `Granite.Widgets.Avatar' could not be found
            var people = new HashMap<string, Granite.Widgets.Avatar>();
                                             ^^^^^^^^^^^^^^^^^^^^^^
/home/dschense/Downloads/birdie-master/src/Widgets/ConversationsList.vala:105.17-105.38: error: The type name `Granite.Widgets.Avatar' could not be found
                Granite.Widgets.Avatar avatar = people.get(name);
                ^^^^^^^^^^^^^^^^^^^^^^
/home/dschense/Downloads/birdie-master/src/Widgets/ConversationsList.vala:107.17-107.38: error: The type name `Granite.Widgets.Avatar' could not be found
                Granite.Widgets.Avatar new_avatar = new Granite.Widgets.Avatar.from_pixbuf(pixbuf);
                ^^^^^^^^^^^^^^^^^^^^^^
/home/dschense/Downloads/birdie-master/src/Birdie.vala:793.13-793.34: error: The type name `Granite.Widgets.Avatar' could not be found
            Granite.Widgets.Avatar avatar = null;
            ^^^^^^^^^^^^^^^^^^^^^^
src/CMakeFiles/birdie.dir/build.make:102: die Regel für Ziel „src/main.c“ scheiterte
make[2]: *** [src/main.c] Fehler 1
CMakeFiles/Makefile2:171: die Regel für Ziel „src/CMakeFiles/birdie.dir/all“ scheiterte
make[1]: *** [src/CMakeFiles/birdie.dir/all] Fehler 2
Makefile:127: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
`

**Comment by dschense** [comment]
found the error:

uninstall granite 0.3.1-1
install granite-bzr r862-1 from aur.

after this it compiles.

starting in terminal runs fine, but get this error:

> [dschense@little build]$ birdie
> Error setting avatar in conversation list: Failed to open file '/usr/share/icons/elementary/status/64/avatar-default.svg': No such file or directory
> [_LEVEL_FATAL 08:55:19.941784] granite_widgets_avatar_construct_from_pixbuf: assertion 'pixbuf != NULL' failed
> [_LEVEL_FATAL 08:55:19.941818] birdie will not function properly.
> [_LEVEL_FATAL 08:55:19.941855] [GLib-GObject] g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed
> [_LEVEL_FATAL 08:55:19.941871] birdie will not function properly.
> [_LEVEL_FATAL 08:55:19.941896] [Gtk] gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
> [_LEVEL_FATAL 08:55:19.941911] birdie will not function properly.
> [_LEVEL_FATAL 08:55:19.941948] [Gtk] gtk_widget_set_margin_left: assertion 'GTK_IS_WIDGET (widget)' failed
> [_LEVEL_FATAL 08:55:19.941964] birdie will not function properly.
> Error setting avatar in conversation list: Failed to open file '/usr/share/icons/elementary/status/64/avatar-default.svg': No such file or directory
> [_LEVEL_FATAL 08:55:28.442251] granite_widgets_avatar_construct_from_pixbuf: assertion 'pixbuf != NULL' failed
> [_LEVEL_FATAL 08:55:28.442335] birdie will not function properly.
> [_LEVEL_FATAL 08:55:28.442425] [GLib-GObject] g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed
> [_LEVEL_FATAL 08:55:28.442536] birdie will not function properly.
> [_LEVEL_FATAL 08:55:28.442673] [Gtk] gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
> [_LEVEL_FATAL 08:55:28.442765] birdie will not function properly.
> [_LEVEL_FATAL 08:55:28.442935] [Gtk] gtk_widget_set_margin_left: assertion 'GTK_IS_WIDGET (widget)' failed
> [_LEVEL_FATAL 08:55:28.442998] birdie will not function properly.
>

**Comment by GMornat** [comment]
Have the same problem here. Can someone provide binaries ?

**Comment by nathandyer** [comment]
Hey all! I'm going to go ahead and close this issue since it isn't a bug in the software itself. Happy to hear that you were able to find a workaround.
