### ISSUE TITLE
Birdie v1.1 crashes immediately on opening

### ISSUE THREAD

**Issue by TonyFlury** [birdieapp/birdie#179]
The main Birdie app window crashes when it is opened - 
have reinstalled - to no avail
deleted /home/<user>/.local/share/birdie to no avail
Despite main window crash - notifications are still given 

[_LEVEL_INFO 09:09:02.366910] Birdie.vala:194: Birdie version: 1.1
[_LEVEL_INFO 09:09:02.366963] Birdie.vala:196: Kernel version: 3.19.0-56-generic
[_LEVEL_FATAL 09:09:04.081873] string_contains: assertion 'self != NULL' failed
[_LEVEL_FATAL 09:09:04.081912] birdie will not function properly.
[_LEVEL_FATAL 09:09:04.081947] string_contains: assertion 'self != NULL' failed
[_LEVEL_FATAL 09:09:04.081975] birdie will not function properly.
[_LEVEL_FATAL 09:09:04.082011] string_contains: assertion 'self != NULL' failed
[_LEVEL_FATAL 09:09:04.082035] birdie will not function properly.
[_LEVEL_FATAL 09:09:04.082756] birdie_tweet_construct: assertion 'youtube_video != NULL' failed
[_LEVEL_FATAL 09:09:04.082785] birdie will not function properly.
[_LEVEL_FATAL 09:09:04.082816] birdie_media_parse_media_url: assertion '*youtube_video != NULL' failed
[_LEVEL_FATAL 09:09:04.082848] birdie will not function properly.
Segmentation fault (core dumped)

**Comment by nathandyer** [comment]
The 1.1 version of Birdie is several years old and has, frankly, been abandoned. A similar issue is happening in 2.0 ( #181 ). I'm closing this issue since it's essentially a duplicate. Still, thank you so much for the report!
