### ISSUE TITLE
Graphic bugs on Ubuntu MATE 15.10

### ISSUE THREAD

**Issue by GMornat** [birdieapp/birdie#180]
![birdie](https://cloud.githubusercontent.com/assets/5551217/14067916/af462f88-f43f-11e5-9683-91a738dc2cdb.png)
The client works pretty good except the header which is blank

PS : Will you remplace Favorite by Likes ?

**Comment by nathandyer** [comment]
Hey! Thanks for the report. Yes, likes will be replacing favorites. The icons have already been changed, although I believe they are still referred to as favorites in some places in the app. We're working on making that more consistent.

As for the graphical bugs, I'm sorry, but we just don't have the resources to support other systems. At this time we only support elementary OS. For more information, please refer to our [announcement post](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html).
