### ISSUE TITLE
Entities problem in Name

### ISSUE THREAD

**Issue by contribucious** [birdieapp/birdie#84]
>**[preamble]**
>_I'm glad to see you again!_
>First of all: wow...!
>What an amazing job on this 2.0-dev!
>And... including Streaming (tweets in real-time): yay!
>
>Except things to come in the final release (clickable avatars/names/hashtags, notifications, etc.), this 2.0-dev is already pretty slick!
>**[/preamble]**

Just found however an old problem of the 1.x version, about the '&' character in Name causing the non-appearance of the Name.
![001](https://cloud.githubusercontent.com/assets/4764956/5260759/b0222158-7a12-11e4-8a61-830b2595acf7.png)
**Try for example this search in Birdie>** from:EetR_National
**Or>** from:Leblogtvnews

```
(birdie:27557): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity - escape ampersand as &amp;
```

No problem else, even with very weird special characters in Name, as long as it's not the '&' one.

**Comment by nathandyer** [comment]
This issue seems to be fixed in version 2.0.
