### ISSUE TITLE
Wrong Screen when Started w/o Internet Connection

### ISSUE THREAD

**Issue by adam3smith** [birdieapp/birdie#87]
When Birdie 2.0 is started without a working internet connection (as is the case for me during system start-up--the WLAN connection takes longer to connect than for Birdie to start up) it doesn't display the "Reconnect Now" screen as Birdie 1 did, but the "Welcome to Birdie. Add/Create Twitter Account" screen. I need to close the app and restart with working internet.
Ubuntu 14.10, can reliably reproduce, let me know if you need any more info.

**Comment by nathandyer** [comment]
Hi! This is fixed in the new 2.0. Thanks for the report!
