### ISSUE TITLE
UTC time is shown, not local

### ISSUE THREAD

**Issue by serge1peshcoff** [birdieapp/birdie#88]
My timezone is GMT+3 and I see posts which were posted, for example, a minute ago, are shown as they were posted 3 hours ago. Let me illustrate it. Here are the posts that were posted not later than 5 minutes  ago.
![screenshot from 2014-12-18 00 10 36](https://cloud.githubusercontent.com/assets/1060257/5479027/68fcef80-864a-11e4-802d-54ab0eb1d1b8.png)

**Comment by Cka3o4Huk** [comment]
Hi,
I had same issue, fixed few days ago (https://github.com/Cka3o4Huk/birdie/commit/ba4bb44dab438253691d6adefff21e568b70d037), so will submit pull request, may be today...  

Best regards,
 Michael

**Comment by Cka3o4Huk** [comment]
Pull request has been created & merged into master.

**Comment by Cka3o4Huk** [comment]
Can issue be closed?

**Comment by nathandyer** [comment]
Hi! This issue should be fixed. I'm going to go ahead and close it. Thank you for the report!

**Comment by Cka3o4Huk** [comment]
Thank you, Nathan! Nice to hear that project is alive. :)
