### ISSUE TITLE
won't build on elementary freya

### ISSUE THREAD

**Issue by ennui-games** [birdieapp/birdie#89]
I attempted to build birdie on elementary freya however configure failed with

    ./configure: line 13834: syntax error near unexpected token `1.35.9'
    ./configure: line 13834: `GOBJECT_INTROSPECTION_REQUIRE(1.35.9)'

I'm sure it's just a missing dependency but I installed all the packages mentioned in birdie/ubuntu_deps.txt

**Comment by neurolit** [comment]
Hi @ennui-games, if you are using Ubuntu, installing libgirepository should solve your problem:

```bash
$ sudo apt-get install libgirepository1.0-dev
```

**Comment by edhemphill** [comment]
I think it might be good to have a list of all required packages on common distros in the readme. That way your likely to get more testers.

On Ubuntu 14.04, here is what I needed, with a machine already meant for development:
sudo apt-get install gnome-common libgirepository1.0-dev yelp-tools libgtk-3-dev

**Comment by Dinduks** [comment]
+1 for having the required packages listed somewhere.
I'd make a PR but I don't know where to put this info. Any idea, repo's owners?

**Comment by nathandyer** [comment]
Required packages are now listed in the INSTALL file. Closing issue.
