### ISSUE TITLE
Packages not available through OS repositories

### ISSUE THREAD

**Issue by flamsmark** [birdieapp/birdie#92]
Birdie packages are only available from the Birdie/GitHub. Since packages are already built specifically for individual distros, they should be made available through those distros' package-managers & repos.

**Comment by nathandyer** [comment]
Hi! I'm sorry, but we recently announced that we are focusing on elementary OS, and are therefore dropping official support for all other Linux platforms. [Please read our announcement post for more information](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html). I should note that Birdie WILL be included in the new elementary App Center once it is available.
