### ISSUE TITLE
Installing on Ubuntu/Linux Mint

### ISSUE THREAD

**Issue by tfgm-bud** [birdieapp/birdie#94]
I had some issues sorting out how to install under Linux Mint/Ubuntu so I thought I'd post this here.  

    git clone https://github.com/birdieapp/birdie.git
    
    sudo apt-get install gnome-common yelp-tools libglib2.0-dev libgirepository1.0-dev libgtk-3-dev
    sudo pip install requests_oauthlib
    
    ./autogen.sh
    make 
    sudo make install

I can update https://github.com/birdieapp/birdie/wiki/How-to-compile if that is appropriate?

-- Bud

**Comment by lioman** [comment]
For Ubuntu 14.04 you need the package `gir1.2-gtksource-3.0` too

**Comment by drewlustro** [comment]
+1

For me, I had to do the following:

`sudo apt-get install auto-conf gnome-tools yelp-tools python-pip`
`sudo pip install requests requests_oauthlib`

And of course, get all the other prerequisite libs specified in the wiki:

`sudo apt-get install cmake valac libgtk-3-dev librest-dev libjson-glib-dev libnotify-dev libcanberra-dev libx11-dev libwebkitgtk-3.0-dev libsqlite3-dev libxtst-dev libpurple-dev libgee-dev libdbusmenu-gtk-dev libgtksourceview-3.0-dev libunity-dev libmessaging-menu-dev libgirepository1.0-dev libindicate-dev`

Then

`./autogen.sh`

Finally, I could `make` and `sudo make install`

**Comment by nathandyer** [comment]
Hi! We recently announced that we are focusing on elementary OS, and are therefore dropping official support for all other Linux platforms. Please check out our [announcement post](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html) for more information. Thank you!
