### ISSUE TITLE
[Debian] Error: Dependency is not satisfiable: libglib2.0-0 (>=2.37.3)

### ISSUE THREAD

**Issue by ghost** [birdieapp/birdie#97]
OS Release: 7.7 (wheezy) 64-bit;
Birdie's installer: birdie_1.1-debian_amd64.deb;
Libglib2.0-0 package installed: 2.33.12+really2.32.4-5 (stable);
Libglib2.0-0 requested by Birdie's installer.: >=2.37.3

**Comment by nathandyer** [comment]
Hi! We recently announced that we are focusing on elementary OS, and are therefore dropping official support for all other Linux platforms. Please read [our announcement post](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html) for more information. Thank you!
