### ISSUE TITLE
Birdie must have own themes

### ISSUE THREAD

**Issue by angelbladex** [birdieapp/birdie#98]
Hi!
If you install birdie 2.0 , you need change theme on your manager desktop.
i prefer suggest birdie must own themes.

**Comment by nathandyer** [comment]
Hi! We don't currently have any plans to support custom themes. Since we [decided to focus on elementary OS](http://www.birdieapp.eu/2016/01/23/building-our-future-on-elementary-os.html), we only officially support the look and feel of Birdie with the native elementary theme.
