### ISSUE TITLE
Graphical bug on Ubuntu 14.04 

### ISSUE THREAD

**Issue by gaetanm** [birdieapp/birdie#99]
I just installed the application on my Ubuntu 14.04 from your PPA and it doesn't show properly:
![screenshot from 2015-01-08 15 58 05](https://cloud.githubusercontent.com/assets/2548394/5664331/ffdc78e2-974f-11e4-99ec-1ebdb052e890.png)

Do I have to install another package?

**Comment by ivonunes** [comment]
This bug is caused by Ubuntu, and we can't fix it. It is caused by the overlay-scrollbar.

**Comment by dschense** [comment]
Ubuntu 14.04
---
disable overlay-scrollbar:

gsettings set com.canonical.desktop.interface scrollbar-mode normal

enable it again:

gsettings reset com.canonical.desktop.interface scrollbar-mode

with disabled overlay-scrollbar everything seems fine
